backend:
  name: github
  repo: App-Procurement/procurement-website
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "xformation"
    label: "Xformation"
    folder: "src/pages/xformation"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "xformation-post",
        }
      - { label: "Title", name: "title", widget: "string" }
  - name: "service"
    label: "Service"
    folder: "src/pages/service"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "service-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Banner Image", name: "bannerimage", widget: "string" }
      - {
          label: "Banner Description",
          name: "bannerdescription",
          widget: "markdown",
        }
      - { label: "Banncer Icon Image", name: "bannericon", widget: "string" }
      - { label: "Banner Icon Name", name: "bannericonname", widget: "string" }
      - {
          label: "Why Us",
          name: "whyus",
          widget: "object",
          fields:
            [
              {
                label: "Show Why us",
                name: "showblock",
                widget: "boolean",
                default: true,
                required: false,
              },
              {
                label: Image,
                name: img,
                widget: string,
                default: false,
                required: false,
              },
              {
                label: Is full image?,
                name: fullimg,
                widget: boolean,
                required: false,
                default: false,
              },
              {
                label: Description,
                name: description,
                widget: markdown,
                default: false,
                required: false,
              },
              {
                label: Product Description,
                name: productdescription,
                widget: markdown,
              },
              { label: Reasons Header, name: reasonstext, widget: markdown },
              {
                label: Reasons,
                name: reasons,
                widget: list,
                fields:
                  [
                    { label: Image, name: img, widget: string },
                    { label: Text, name: text, widget: string },
                    { label: Description, name: description, widget: markdown },
                  ],
              },
              { label: Conclusion, name: conclusion, widget: markdown },
              { label: Conclusion Image, name: conclusionimg, widget: string },
            ],
        }
      - {
          label: "Aproach",
          name: "aproach",
          widget: "object",
          fields:
            [
              {
                label: "Show Aproach",
                name: "showblock",
                widget: "boolean",
                default: true,
                required: false,
              },
              { label: Banner Image, name: img, widget: string },
              {
                label: Banner Description,
                name: description,
                widget: markdown,
                required: false,
              },
              {
                label: Actions,
                name: actions,
                widget: list,
                fields:
                  [
                    {
                      label: Is Side Image?,
                      name: issideimage,
                      widget: boolean,
                      default: true,
                    },
                    { label: Image, name: img, widget: string },
                    { label: Heading, name: heading, widget: string },
                    { label: Description, name: text, widget: markdown },
                  ],
              },
            ],
        }
      - {
          label: "Getting Started",
          name: "gettingstarted",
          widget: "object",
          fields:
            [
              {
                label: "Show Getting started",
                name: "showblock",
                widget: "boolean",
                default: true,
                required: false,
              },
              {
                label: Actions,
                name: actions,
                widget: list,
                fields:
                  [
                    { label: Image, name: img, widget: text },
                    { label: Description, name: description, widget: markdown },
                    {
                      label: Header,
                      name: heading,
                      widget: text,
                      required: false,
                    },
                  ],
              },
              { label: Testimonial, name: testimonial, widget: string },
            ],
        }
      - {
          label: "Resources",
          name: "resources",
          widget: "object",
          fields:
            [
              {
                label: "Show Resources",
                name: "showblock",
                widget: "boolean",
                default: true,
                required: false,
              },
              {
                label: "Blogs",
                name: "blogs",
                widget: "list",
                fields:
                  [
                    { label: Image, name: img, widget: string },
                    { label: Heading, name: heading, widget: string },
                    { label: Description, name: description, widget: string },
                    { label: Link, name: link, widget: string },
                  ],
              },
              {
                label: "White papers",
                name: "whitepapers",
                widget: "list",
                fields:
                  [
                    { label: Image, name: img, widget: string },
                    { label: Heading, name: heading, widget: string },
                    { label: Description, name: description, widget: string },
                    { label: Link, name: link, widget: string },
                  ],
              },
              {
                label: "Case studies",
                name: "casestudies",
                widget: "list",
                fields:
                  [
                    { label: Image, name: img, widget: string },
                    { label: Heading, name: heading, widget: string },
                    { label: Description, name: description, widget: string },
                    { label: Link, name: link, widget: string },
                  ],
              },
            ],
        }
      - { label: "Category", name: "category", widget: "list" }
  - name: "pagerendererpost"
    label: "Page Renderer Post"
    folder: "src/pages/pagerendererpost"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "page-renderer-page",
        }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Pagerenderer JSON",
          name: "pagerendererjson",
          widget: "object",
          fields: [{ label: "Data", name: "data", widget: "text" }],
        }
  - name: "workflowpost"
    label: "Workflow Post"
    folder: "src/pages/workflowpost"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "workflow-page",
        }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Workflow JSON",
          name: "workflowjson",
          widget: "object",
          fields: [{ label: "Data", name: "data", widget: "text" }],
        }
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templatekey",
              widget: "hidden",
              default: "scenario-post",
            }
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: Actors List,
              name: scenarios,
              widget: list,
              fields:
                [
                  { label: Image, name: img, widget: text },
                  { label: Name, name: name, widget: text },
                  {
                    label: "Use cases",
                    name: "subItems",
                    widget: "list",
                    fields:
                      [
                        { label: Image, name: img, widget: text },
                        { label: Name, name: name, widget: text },
                        {
                          label: "Use Case Slider",
                          name: "useCaseSlider",
                          widget: "list",
                          fields:
                            [
                              { label: Image, name: img, widget: text },
                              { label: Name, name: name, widget: text },
                              { label: Text, name: text, widget: text },
                            ],
                        },
                      ],
                  },
                ],
            }
          - {
              label: "Slider",
              name: "slider",
              widget: "list",
              fields:
                [
                  { label: Image, name: img, widget: text },
                  { label: Name, name: name, widget: text },
                  { label: Text, name: text, widget: text },
                  {
                    label: "More Details",
                    name: "moreDetails",
                    widget: "object",
                    fields:
                      [
                        {
                          label: More Details Name,
                          name: moreDetailsName,
                          widget: text,
                        },
                        {
                          label: More Details Text,
                          name: moreDetailsText,
                          widget: text,
                        },
                        {
                          label: More Details Image,
                          name: moreDetailsImage,
                          widget: list,
                          fields: [{ label: Image, name: img, widget: text }],
                        },
                      ],
                  },
                ],
            }
  - name: "newDashboard"
    label: "New Dashboard"
    folder: "src/pages/index.md"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templatekey",
          widget: "hidden",
          default: "new-dashboard-page",
        }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: Actors List,
          name: scenarios,
          widget: list,
          fields:
            [
              { label: Image, name: img, widget: text },
              { label: Name, name: name, widget: text },
              {
                label: "Use cases",
                name: "subItems",
                widget: "list",
                fields:
                  [
                    { label: Image, name: img, widget: text },
                    { label: Name, name: name, widget: text },
                    {
                      label: "Use Case Slider",
                      name: "useCaseSlider",
                      widget: "list",
                      fields:
                        [
                          { label: Image, name: img, widget: text },
                          { label: Name, name: name, widget: text },
                          { label: Text, name: text, widget: text },
                        ],
                    },
                  ],
              },
            ],
        }
      - {
          label: "Slider",
          name: "slider",
          widget: "list",
          fields:
            [
              { label: Image, name: img, widget: text },
              { label: Name, name: name, widget: text },
              { label: Text, name: text, widget: text },
              {
                label: "More Details",
                name: "moreDetails",
                widget: "object",
                fields:
                  [
                    {
                      label: More Details Name,
                      name: moreDetailsName,
                      widget: text,
                    },
                    {
                      label: More Details Text,
                      name: moreDetailsText,
                      widget: text,
                    },
                    {
                      label: More Details Image,
                      name: moreDetailsImage,
                      widget: list,
                      fields: [{ label: Image, name: img, widget: text }],
                    },
                  ],
              },
            ],
        }
